### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [maielo/pdftk-fill-pdf#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by maielo** [comment]
Hello,

Thank you for the offer, you can go ahead. 

Initial need was quickly do it for my client, but now i got some free time to actually make it more performant, remove unnecesary packages (like bluebird), use `fs/promisfy` instead of writing promises and add some more features i had in mind. the TS would be great start, so i could iterate on it later on.

**Comment by geopic** [comment]
Nice one. It'll just be a file which acts as documentation like JSDoc and suchlike. I'll get started on it now. :+1:
